micronaut:
  application:
    name: pix

grpc:
  client:
    plaintext: true
    max-retry-attempts: 5
  channels:
    pix:
      address: ${APPLICATION_HOST:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 5

#
#datasources:
#  default:
#    url: jdbc:mysql://localhost:3306/banco_pix
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: password
#    schema-generate: CREATE_DROP
#    dialect: MYSQL
#jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
#jpa.default.properties.hibernate.show_sql: true
